### ISSUE TITLE
GUI shows incorrect arm status when armed on ground

### ISSUE THREAD

**Issue by hiradg** [UoBFlightLab/mav_missions#19]
Drone arm status is shown as disarmed when the drone is armed on ground; changes to armed after take off.

**Comment by arthurrichards77** [comment]
I think this is a latency thing.  In the current takeoff protocol, which we know doesn't work in the field anyway, the drone is always in AUTO and the waypoint counter is advanced to 2 by CLRTO, which puts you on a takeoff command.  If you then arm, the drone executes the takeoff.  But the heartbeat messages that convey the arming status only come in at 1Hz, so you're typically in the air before the new status comes in.  Perhaps there's another source of latency in the processing as well.  Anyway, I'm not sure this is actually a bug, so much as an undesirable feature.

It might be possible to intercept an additional status message that indicates the arming earlier - but that adds complexity and does it really solve a problem?

**Comment by hiradg** [comment]
Addressing issue #19. The arm_disarm status was observed using the [MAV_STATE](https://mavlink.io/en/messages/common.html#MAV_STATEl) message. MAV_STATE is not suitable for arm status since it reports standby and in the air props spinning (along with other emergency states) rather than arm status. We now look at [MAV_MODE](https://mavlink.io/en/messages/common.html#MAV_MODE).
