### ISSUE TITLE
Fail safe switch

### ISSUE THREAD

**Issue by arthurrichards77** [UoBFlightLab/mav_missions#22]
Can we monitor and display the safety switch setting in the GUI?  Reading the RC channels would do it, but seems brittle.  Is it encoded in a status message somwhere?

**Comment by hiradg** [comment]
Yes we can. 

We currently use the [Motor EStop RC function](https://ardupilot.org/copter/docs/common-auxiliary-functions.html) on the transmitter as a preflight safety switch and a kill switch if needed. This is a an ardupilot specific RC command with no direct mavlink mapping. However ardupilot does update the pre-arm status.

Learning from [mavproxy](https://github.com/ArduPilot/MAVProxy/blob/2f6b91f0c562af580debd7db25e34b4362eca3c5/MAVProxy/modules/mavproxy_swarm.py#L722-L723) and [mission planner](https://github.com/ArduPilot/MissionPlanner/blob/f094171521ed10860cf56b2c0871b2d445d848b8/ExtLibs/ArduPilot/CurrentState.cs#L4219-L4220) we can use the pre-am status as both indication of ready-to-arm and EStop status at the same time.
