### ISSUE TITLE
GUI is now too wide (needs to go on a diet)

### ISSUE THREAD

**Issue by hiradg** [UoBFlightLab/mav_missions#43]
We have added status monitoring and preflight check items to the gui which are essential for our operation. However its too wide for some screens and the last clearance tab gets clipped on my laptop screen.

I suggest renaming some of the title tabs.

**Comment by arthurrichards77** [comment]
Could put the heartbeat indication over the system ID label rather than its own column.

**Comment by arthurrichards77** [comment]
Maybe separate clearance controls from status information.  Replace with block indicators.
