### ISSUE TITLE
control_gui refactor

### ISSUE THREAD

**Issue by arthurrichards77** [UoBFlightLab/mav_missions#44]
Our `ControlGui` class has got bloated and difficult to maintain.  Linting reports excessive attributes and numbers of statements. 
 Suggest:
- separating out a `build_gui` method from the `__init__` method
- moving the clearance logic to the jump controller (see #30)
- making dictionaries of buttons, labels and vars: `self.btns['upload'][1]` etc
- having standard helper functions to build columns of almost-identical labels and buttons
- help functions to change label colours, text, and add a blinking symbol for each update (as heartbeat and param do)

**Comment by arthurrichards77** [comment]
Related point: I think it would be more scalable if we provided a list of drone IDs rather than 1 to N.  Then the arrays of buttons etc would be better as dictionaries, e.g. `self.labels['params'] = {'all':'Params', 1:'OK', 2:'Fail'}`  Not that you'd construct or write that.  ControlGui constructor would now take `sys_ids` as argument and interpret it as an array of IDs to show.  Command line could accept either a max ID, thus setting `sys_ids=range(1,max_id)` or an explicit list, `-i 1 3 4 5`

**Comment by mhl787156** [comment]
I have been doing some analysis, and I'm thinking that we take it a step further from what you suggest @arthurrichards77 and may as well properly follow Model-View-Control (MVC) architecture. The suggestions you make take us almost all of the way there anyway! 

In our case:
- Model(s): Mavlink connection, Jump controller, mission uploader, param checker etc. 
- View: GUI construction (refactored by row), Button press commands change the controller to modify the model
- Controller: Links the model and the view, as well as initialises everything. 

This should pull everything apart and make it both more maintainable as well as enforcing seperation of concerns. 

Practically, this will mostly be copy pasting and splitting out the control_gui into multiple classes and files. I will give it a start now.

**Comment by arthurrichards77** [comment]
I agree with your suggestion @mhl787156 - and if I understand it right, that would give us the opportunity to add test code for the logic by talking directly to the controller, without having to figure out how to run auto testing through a GUI.  GOod for you to get your head in the codebase as well, for future support.

Please do crack on with a branch and we'll run a quick review when @hiradg gets back.
