### ISSUE TITLE
Interlock jumps and blocks

### ISSUE THREAD

**Issue by arthurrichards77** [UoBFlightLab/mav_missions#50]
Various ways to do it:
 - prevent clearances being issued before all suitable blocks are available
 - prevent jumps acting if required blocks aren't available (could jumps with the same clearances have different block requirements?)

Also could determine block/jump interconnects at analysis time, automatically, or define them at design time and then postprocess to check for violations.

**Comment by mhl787156** [comment]
This is now completed with #52
