### ISSUE TITLE
Separate monitor from experiment

### ISSUE THREAD

**Issue by arthurrichards77** [UoBFlightLab/mav_missions#53]
App 1: rows showing mode, parameters, alt etc

App 2: blocks, jumps, routes, etc

**Comment by mhl787156** [comment]
Currently planning to split this into two separate modules with two separate mavlink streams.

**Comment by mhl787156** [comment]
I have split into into a `fleet_status_monitor` and `mav_missions`. The monitor page is:

![image](https://github.com/UoBFlightLab/mav_missions/assets/10742598/dce70c09-0f0e-44f7-8ef2-b8618dea3ac2)

@arthurrichards77 please could you verify what columns you would like? 

I am under the assumption that this should be completely separate from the vertiport functionality. Therefore I have removed mission upload and clearances. It makes sense for it to retain the parameter upload and check functionality though.
